### ISSUE TITLE
ClaimControl is a trademarked name. Can you please rename your add-in

### ISSUE THREAD

**Issue by BrianBoyce** [ty2u/ClaimControl#2]
Hi,

I appreciate this is a purely coincidental infringement but it is just to let you know that ClaimControl is a trademarked name of alphatec software limited (www.alphatec.net). Can I please ask you to rename your add-in so that there is no conflict.

If you need to contact me please e-mail me at removed and if you want we can discuss this over the phone.
Thanks for your help
Brian

**Comment by ty2u** [comment]
Hi there,

Alright no problem. Sorry, I wasn't aware that word existed already. We made it up when we were playing on the server creating this plugin a few years back. It can fairly easily be renamed anything though. Guessing it must be competing with search rankings or something? Sorry about that!

I removed your email address so you don't get spam from it.

Ryan

**Comment by BrianBoyce** [comment]
Thanks Ryan,

Yes its mainly because of competing search. I can see it clearly isnt a competitor product or anything like that. Thanks I appreciate you getting back to me on this - and thanks for removing my email.
Brian
